"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useAdmin } from "@/lib/admin-context";
import { Button, MetricCard, PageHeader, Section, SparkChart, StatusBadge, money } from "@/components/ui";

export function DashboardScreen(){
 const {state,branchId}=useAdmin();const[range,setRange]=useState("Today");
 const orders=useMemo(()=>state.orders.filter(o=>branchId==="all"||o.branchId===branchId),[state.orders,branchId]);const revenue=orders.reduce((a,b)=>a+b.total,0);const delivery=orders.filter(o=>o.type==="Delivery").length;
 return <><PageHeader title="Good morning, Amelia" description="Here’s what needs attention across Maeme’s today." actions={<><select aria-label="Date range" value={range} onChange={e=>setRange(e.target.value)}><option>Today</option><option>Yesterday</option><option>Last 7 days</option><option>Last 30 days</option><option>Custom range</option></select><Button onClick={()=>window.print()}>Export snapshot</Button></>}/>
 <div className="metrics-grid"><MetricCard label="Today’s revenue" value={money(revenue)} detail="+12.4% vs yesterday" icon="£"/><MetricCard label="Today’s orders" value={String(orders.length)} detail="6 awaiting action" icon="▤"/><MetricCard label="Average order value" value={money(revenue/Math.max(orders.length,1))} detail="+£1.82 this week" icon="↗"/><MetricCard label="New customers" value={String(state.customers.length)} detail="3 opted into marketing" icon="+"/><MetricCard label="Delivery orders" value={String(delivery)} detail={`${Math.round(delivery/Math.max(orders.length,1)*100)}% of orders`} icon="⌁"/><MetricCard label="Collection orders" value={String(orders.length-delivery)} detail="18 min average" icon="⌂"/><MetricCard label="Active branches" value={`${state.branches.filter(b=>b.active).length}/${state.branches.length}`} detail="1 branch closed" icon="⌖"/><MetricCard label="Pending refunds" value={String(state.orders.filter(o=>o.status==="Refund Requested").length)} detail="Requires finance review" icon="↩"/></div>
 <div className="dashboard-grid"><Section title="Revenue trend" description={`${range} · comparison with previous period`} action={<StatusBadge tone="success">+12.4%</StatusBadge>}><div className="big-chart"><SparkChart values={[42,55,49,67,61,78,84]}/><div className="chart-labels"><span>08:00</span><span>12:00</span><span>16:00</span><span>20:00</span></div></div></Section>
 <Section title="Order status" description="Current operational pipeline"><div className="status-bars">{["New","Confirmed","Preparing","Ready for Collection","Out for Delivery"].map((s,i)=>{const count=orders.filter(o=>o.status===s).length;return <div key={s}><span>{s}<b>{count}</b></span><i><em style={{width:`${Math.max(8,count*22)}%`}}/></i></div>})}</div></Section></div>
 <div className="dashboard-grid lower"><Section title="Recent orders" description="Most recent activity across selected branches" action={<Link href="/orders">View all →</Link>}><div className="compact-list">{orders.slice(0,6).map(o=><Link href={`/orders/${o.id}`} key={o.id}><span><b>{o.number}</b><small>{o.customer} · {o.type}</small></span><span><b>{money(o.total)}</b><StatusBadge>{o.status}</StatusBadge></span></Link>)}</div></Section>
 <Section title="Operational attention" description="Items that may affect service"><div className="alerts"><Link href="/branches/bromley"><i className="danger">!</i><span><b>Bromley branch is closed</b><small>Delivery has been disabled</small></span></Link><Link href="/payments"><i className="warning">£</i><span><b>2 failed demo payments</b><small>Review provider placeholders</small></span></Link><Link href="/menu/products"><i className="warning">◇</i><span><b>Chocolate Cake Slice unavailable</b><small>Across all active branches</small></span></Link></div></Section></div>
 <Section title="Performance at a glance" description="Products and branch comparison"><div className="performance-grid"><div><h3>Top-selling products</h3>{state.products.slice(0,5).map((p,i)=><div className="rank-row" key={p.id}><b>{i+1}</b><span>{p.name}<small>{p.category}</small></span><strong>{52-i*7} orders</strong></div>)}</div><div><h3>Branch performance</h3>{state.branches.map((b,i)=><div className="rank-row" key={b.id}><b>{i+1}</b><span>{b.name}<small>{b.delivery?"Delivery & Collection":"Collection only"}</small></span><strong>{money(1240-i*185)}</strong></div>)}</div></div></Section>
 </>;
}
