"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { roles } from "@/lib/mock-data";
import { useAdmin } from "@/lib/admin-context";
import type { RoleId } from "@/lib/types";
import { Button, Input } from "@/components/ui";

export function AuthScreen({mode="login"}:{mode?:"login"|"forgot"|"reset"}){
 const {login}=useAdmin();const router=useRouter();const [role,setRole]=useState<RoleId>("super-admin"),[busy,setBusy]=useState(false),[sent,setSent]=useState(false);
 if(mode!=="login")return <div className="auth-page"><section className="auth-card"><div className="auth-brand"><span className="brand-mark">M</span><div><b>Maeme’s</b><small>Admin Management Control</small></div></div><p className="prototype-pill">Frontend prototype · no real account email is sent</p><h1>{mode==="forgot"?"Reset demo access":"Choose a new demo password"}</h1><p>{mode==="forgot"?"Enter a fictional work email to preview the reset confirmation.":"This form demonstrates validation only and stores no password."}</p>{sent?<div className="success-box">✓ Demo confirmation complete. You can return to sign in.</div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}>{mode==="forgot"?<Input label="Work email" type="email" defaultValue="admin@example.test" required/>:<><Input label="New demo password" type="password" minLength={8} required/><Input label="Confirm demo password" type="password" minLength={8} required/></>}<Button type="submit">{mode==="forgot"?"Send demo link":"Reset demo password"}</Button></form>}<button className="text-button" onClick={()=>router.push("/login")}>← Back to login</button></section><AuthAside/></div>;
 return <div className="auth-page"><section className="auth-card"><div className="auth-brand"><span className="brand-mark">M</span><div><b>Maeme’s</b><small>Admin Management Control</small></div></div><p className="prototype-pill">Frontend-only operational prototype</p><h1>Welcome back</h1><p>Select a fictional staff role to explore its permitted workspace. No credentials are required or stored.</p><div className="role-grid">{roles.map(r=><button type="button" key={r.id} className={role===r.id?"selected":""} onClick={()=>setRole(r.id)}><span>{r.name.split(" ").map(v=>v[0]).join("")}</span><div><b>{r.name}</b><small>{r.description}</small></div><i>{role===r.id?"✓":""}</i></button>)}</div><Button disabled={busy} onClick={async()=>{setBusy(true);await login(role);router.push("/dashboard")}}>{busy?"Starting demo session…":"Continue to dashboard"} →</Button><button className="text-button" onClick={()=>router.push("/forgot-password")}>Forgot demo access?</button><p className="auth-safe">🔒 Fictional data only · Mock actions are not connected to a backend.</p></section><AuthAside/></div>
}
function AuthAside(){return <aside className="auth-aside"><div><p>Restaurant operations, thoughtfully organised.</p><h2>One clear view of every Maeme’s service.</h2><ul><li><b>Live-style operations</b><span>Orders, fulfilment and branch health</span></li><li><b>Controlled catalogue</b><span>Products, modifiers and availability</span></li><li><b>Safe governance</b><span>Roles, audit events and mock finance</span></li></ul></div><small>Prototype environment · July 2026</small></aside>}
