"use client";
import { useEffect, useId, useState } from "react";
import Link from "next/link";
import type { StatusTone } from "@/lib/types";

export const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(n);
export function Button({children,variant="primary",className="",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"danger"|"ghost"}){return <button className={`btn btn-${variant} ${className}`} {...props}>{children}</button>}
export function StatusBadge({children,tone}: {children:React.ReactNode;tone?:StatusTone}){const text=String(children).toLowerCase();const inferred=tone??(text.includes("open")||text.includes("active")||text.includes("paid")||text.includes("delivered")||text.includes("success")?"success":text.includes("fail")||text.includes("cancel")||text.includes("closed")||text.includes("suspend")?"danger":text.includes("pending")||text.includes("soon")||text.includes("preparing")||text.includes("scheduled")?"warning":"neutral");return <span className={`badge badge-${inferred}`}>{children}</span>}
export function MetricCard({label,value,detail,icon}:{label:string;value:string;detail:string;icon:string}){return <article className="metric"><span className="metric-icon" aria-hidden>{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article>}
export function PageHeader({title,description,actions}:{title:string;description:string;actions?:React.ReactNode}){return <header className="page-header"><div><p className="eyebrow">Maeme’s operations</p><h1>{title}</h1><p>{description}</p></div>{actions&&<div className="page-actions">{actions}</div>}</header>}
export function SearchInput({value,onChange,placeholder="Search records…"}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="search"><span aria-hidden>⌕</span><span className="sr-only">Search</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button onClick={()=>onChange("")} aria-label="Clear search">×</button>}</label>}
export function Select({label,className="",...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{label:string}){return <label className={`field ${className}`}><span>{label}</span><select {...props}/></label>}
export function Input({label,helper,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;helper?:string}){return <label className="field"><span>{label}{props.required&&<b aria-label="required"> *</b>}</span><input {...props}/>{helper&&<small>{helper}</small>}</label>}
export function Textarea({label,...props}:React.TextareaHTMLAttributes<HTMLTextAreaElement>&{label:string}){return <label className="field"><span>{label}</span><textarea {...props}/></label>}
export function Switch({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="switch-row"><span>{label}</span><button type="button" role="switch" aria-checked={checked} onClick={()=>onChange(!checked)} className={`switch ${checked?"on":""}`}><i/></button></label>}
export function Tabs({tabs,active,onChange}:{tabs:string[];active:string;onChange:(v:string)=>void}){return <div className="tabs" role="tablist">{tabs.map(t=><button role="tab" aria-selected={active===t} key={t} onClick={()=>onChange(t)}>{t}</button>)}</div>}
export function EmptyState({title="No records found",description="Try clearing the current filters."}:{title?:string;description?:string}){return <div className="empty"><span aria-hidden>◇</span><h3>{title}</h3><p>{description}</p></div>}
export function Skeleton({rows=5}:{rows?:number}){return <div className="skeleton-list" aria-label="Loading">{Array.from({length:rows},(_,i)=><i key={i}/>)}</div>}
export function Dialog({open,title,children,onClose}:{open:boolean;title:string;children:React.ReactNode;onClose:()=>void}){const id=useId();useEffect(()=>{const close=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();if(open)window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[open,onClose]);if(!open)return null;return <div className="dialog-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby={id}><header><h2 id={id}>{title}</h2><button aria-label="Close dialog" onClick={onClose}>×</button></header>{children}</section></div>}
export function Toasts({items}:{items:{id:number;message:string;tone:string}[]}){return <div className="toasts" aria-live="polite">{items.map(t=><div key={t.id} className={`toast ${t.tone}`}>{t.tone==="success"?"✓":"!"} {t.message}</div>)}</div>}
export function DataTable<T extends {id:string}>({rows,columns,selected,onSelect}:{rows:T[];columns:{key:string;label:string;render:(row:T)=>React.ReactNode}[];selected?:string[];onSelect?:(id:string)=>void}){if(!rows.length)return <EmptyState/>;return <><div className="table-wrap"><table><thead><tr>{onSelect&&<th><span className="sr-only">Select</span></th>}{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{onSelect&&<td><input type="checkbox" aria-label={`Select ${r.id}`} checked={selected?.includes(r.id)} onChange={()=>onSelect(r.id)}/></td>}{columns.map(c=><td key={c.key} data-label={c.label}>{c.render(r)}</td>)}</tr>)}</tbody></table></div><div className="mobile-records">{rows.map(r=><article key={r.id}>{columns.slice(0,5).map(c=><div key={c.key}><small>{c.label}</small><span>{c.render(r)}</span></div>)}</article>)}</div></>}
export function Pagination({page,total,pageSize,onChange}:{page:number;total:number;pageSize:number;onChange:(n:number)=>void}){const pages=Math.max(1,Math.ceil(total/pageSize));return <nav className="pagination" aria-label="Pagination"><span>{total} records</span><div><Button variant="secondary" disabled={page<=1} onClick={()=>onChange(page-1)}>Previous</Button><span>Page {page} of {pages}</span><Button variant="secondary" disabled={page>=pages} onClick={()=>onChange(page+1)}>Next</Button></div></nav>}
export function SparkChart({values,color="#99041E"}:{values:number[];color?:string}){const max=Math.max(...values);const points=values.map((v,i)=>`${(i/(values.length-1))*100},${50-(v/max)*42}`).join(" ");return <svg viewBox="0 0 100 52" role="img" aria-label="Trend chart"><path d="M0 50H100" stroke="#eadfd6"/><polyline points={points} fill="none" stroke={color} strokeWidth="2.5" vectorEffect="non-scaling-stroke"/>{values.map((v,i)=><circle key={i} cx={(i/(values.length-1))*100} cy={50-(v/max)*42} r="1.7" fill={color}/>)}</svg>}
export function LinkButton({href,children}:{href:string;children:React.ReactNode}){return <Link className="btn btn-primary" href={href}>{children}</Link>}
export function Section({title,description,children,action}:{title:string;description?:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="panel"><header className="panel-head"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</header>{children}</section>}
export function useDelayedReady(delay=280){const[ready,setReady]=useState(false);useEffect(()=>{const t=setTimeout(()=>setReady(true),delay);return()=>clearTimeout(t)},[delay]);return ready}
